# Python for Spatial Analysis
## Second part of the module of GG3209 Spatial Analysis with GIS.
### Notebook to practice NumPy and Pandas - Exercises

---
Dr Fernando Benitez -  University of St Andrews - School of Geography and Sustainable Development - First Iteration 2023 v.1.0 

# Practicing NumPy

## 2.0 
Import numpy under the alias `np`.

In [2]:
import numpy as np

## 2.1 

Create the following arrays:

* Create an array of 10 ones.

* Create an array of the integers 1 to 20.

* Create a 5 x 5 matrix of ones with a dtype int.

In [15]:
arr1 = np.tile(1, 10)
print(arr1)

arr2 = np.arange(1, 21, 1, dtype="int")
print(arr2)

arr3= np.ones((1,5,5))
print(arr3)



[1 1 1 1 1 1 1 1 1 1]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


## 2.2 
Use numpy to:
1. Create an 3D matrix of 3 x 3 x 3 full of random numbers drawn from a standard normal distribution (hint: `np.random.randn()`)
2. Reshape the above array into shape (27,)

In [4]:
arr4 = np.random.rand(1, 3, 3)
print(arr4)

arr5 = np.random.rand(1,27,1)
print(arr5)



[[[5.86701395e-01 9.18076778e-01 1.90436635e-04]
  [7.26202773e-01 6.73238988e-01 9.14295073e-02]
  [5.58304421e-02 6.91609010e-01 9.08764603e-01]]]
[[[0.0508695 ]
  [0.83595539]
  [0.82493906]
  [0.25908186]
  [0.76187214]
  [0.89855927]
  [0.61569198]
  [0.99449941]
  [0.23673924]
  [0.48573832]
  [0.72643431]
  [0.58006374]
  [0.18559177]
  [0.75713723]
  [0.25748731]
  [0.50144239]
  [0.41750884]
  [0.28657532]
  [0.49504952]
  [0.64115592]
  [0.35995108]
  [0.26898936]
  [0.34609655]
  [0.28021112]
  [0.61587354]
  [0.0666708 ]
  [0.86794514]]]


# 2.3 

Create an array of 20 linearly spaced numbers between 1 and 10.

In [7]:
arr6 = np.arange(1, 10.5, 0.5)
print(arr6)


[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10. ]


## 2.4

Run the following code to create an array of shape 4 x 4 and then use indexing to produce the outputs shown below.

In [2]:
import numpy as np
a = np.arange(1, 26).reshape(5, -1)

In [3]:
arr7 = a
print(arr7)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [5]:
#Code goes here
#Code goes here
lst1 = [[9, 10, 14, 15, 19, 20, 24, 25]]
arr8 = np.array(lst1)
print(arr8)
arr8.reshape(-1, 4, 2)



[[ 9 10 14 15 19 20 24 25]]


array([[[ 9, 10],
        [14, 15],
        [19, 20],
        [24, 25]]])

```python
array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])
```

In [ ]:
# Code come here


```python
array([ 6,  7,  8,  9, 10])
```

In [6]:
lst2 = [6, 7, 8, 9, 10]
arr9 = np.array(lst2)
print(arr9)
arr9.reshape(-1, 1, 5)


[ 6  7  8  9 10]


array([[[ 6,  7,  8,  9, 10]]])

## 2.5 

Calculate the sum of all the numbers in `a`.

In [21]:
# Code comes here

arr10 = np.arange(1, 26, 1, dtype="int")
print(arr10)
np.sum(arr10)




[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]


325

## 2.6 

Calculate the sum of each row in `a`.

In [34]:
# Code comes here

arr11 = arr7.reshape(5,1,5)

print(arr11[0])
np.sum(arr11[0])


[[1 2 3 4 5]]


15

In [35]:
print(arr11[1])
np.sum(arr11[1])

[[ 6  7  8  9 10]]


40

In [36]:
print(arr11[2])
np.sum(arr11[2])

[[11 12 13 14 15]]


65

In [37]:
print(arr11[3])
np.sum(arr11[3])

[[16 17 18 19 20]]


90

In [38]:
print(arr11[4])
np.sum(arr11[4])

[[21 22 23 24 25]]


115

## 2.7 

Extract all values of `a` greater than the mean of `a` (hint: use a boolean mask).

In [44]:
# Code comes here
np.mean(arr11)

13.0

In [48]:
arr11b = arr11 > 13
print(arr11b)

[[[False False False False False]]

 [[False False False False False]]

 [[False False False  True  True]]

 [[ True  True  True  True  True]]

 [[ True  True  True  True  True]]]


# Practicing Pandas

## 2.8

In this set of practice exercises we'll be investigating the carbon footprint of different foods. 

We'll be leveraging a dataset compiled by [Kasia Kulma](https://r-tastic.co.uk/post/from-messy-to-tidy/) and contributed to [R's Tidy Tuesday project](https://github.com/rfordatascience/tidytuesday).

Start by importing pandas with the alias `pd`.

In [49]:
# Codes comes here
import numpy as np
import pandas as pd

## 2.9 

The dataset we'll be working with has the following columns:

|column      |description |
|:-------------|:-----------|
|country       | Country Name |
|food_category | Food Category |
|consumption   | Consumption (kg/person/year) |
|co2_emmission | Co2 Emission (Kg CO2/person/year) |


Import the dataset as a dataframe named `df` from this url: <https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv>

In [ ]:
# Code comes here

## 2.10 

How many rows and columns are there in the dataframe?

In [ ]:
#Code comes here

## 2.11

What is the mean `co2_emission` of the whole dataset?

In [ ]:
# Code comes here

## 2.12

What is the maximum `co2_emmission` in the dataset and which food type and country does it belong to?

In [ ]:
# Code comes here

## 2.13

How many countries produce more than 1000 Kg CO2/person/year for at least one food type?

In [ ]:
#code comes here

## 2.14

Which country consumes the least amount of beef per person per year?


In [ ]:
# code comes here

## 2.15

What is the total emissions of all the meat products (Pork, Poultry, Fish, Lamb & Goat, Beef) in the dataset combined?

In [ ]:
# code comes here

# 2.16 

What is the total emissions of all other (non-meat) products in the dataset combined?

In [ ]:
# code comes here

## Well done!

That's all from this week, if you have any questions, do not forget to ask the TAs for assistance.